const char ANDROIDMANIFESTXML_STR[] = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\n"
"      package=\"com.fi.tech.%s\"\n"
"      android:versionCode=\"1\"\n"
"      android:versionName=\"%s\">\n"
"\n"
"    <uses-permission android:name=\"android.permission.WAKE_LOCK\" />  \n"
"\n"
"    <application android:label=\"@string/app_name\" android:icon=\"@drawable/icon\">\n"
"        <activity android:name=\".Paper3D\"\n"
"                  android:theme=\"@android:style/Theme.NoTitleBar.Fullscreen\"\n"
"                  android:launchMode=\"singleTask\"\n"
"                  android:configChanges=\"orientation|keyboardHidden\"\n"
"                  android:screenOrientation=\"portrait\"\n"
"                  android:keepScreenOn=\"true\"        \n"
"                  android:label=\"@string/app_name\">\n"
"            <intent-filter>\n"
"                <action android:name=\"android.intent.action.MAIN\" />\n"
"                <category android:name=\"android.intent.category.LAUNCHER\" />\n"
"            </intent-filter>\n"
"        </activity>\n"
"    </application>\n"
"    <uses-feature android:glEsVersion=\"0x00020000\"/>\n"
"    <uses-sdk\n"
"        android:minSdkVersion=\"9\"\n"
"        android:targetSdkVersion=\"9\" />\n"
"</manifest> \n"
"\n"
;
