const char MYSCENECPP_STR[] = 
"// myscene.cpp\n"
"%s\n"
"\n"
"#include \"myscene.h\"\n"
"\n"
"#include <Paper3D/paper3d.h>\n"
"\n"
"#include <PFoundation/pfoundation.h>\n"
"\n"
"\n"
"MyScene::MyScene(PContext *context)\n"
"    : PScene(\"my-scene\", context)\n"
"{\n"
"    PResourceManager *resMgr = context->module<PResourceManager>(\"resource-manager\");\n"
"\n"
"    if (!load(\"scene.psc\")) \n"
"    {\n"
"        PASSERT(!\"Failed to load scene.psc\");\n"
"        return ;\n"
"    }\n"
"}\n"
"\n"
"MyScene::~MyScene()\n"
"{\n"
"}\n"
"    \n"
"void MyScene::update()\n"
"{\n"
"	PVector3 r = root()->transform().rotation();\n"
"	r[2] -= 0.01f;\n"
"	root()->transform().setRotation(r);\n"
"}\n"
;
