// project.h
// Define the project directory structure
//
// Copyright 2012 - 2014 Future Interface. 
// This software is licensed under the terms of the MIT license.
//
// Hongwei Li lihw81@gmail.com
//

#ifndef PROJECT_H
#define PROJECT_H


static char panel3DProjectConf[] = 
"+<project-name>\n"
"  +application\n"
"    +configs\n"
"      +msvc2012\n"
"        -<project-name>.sln <project-name> <project-name>\n"
"        -<project-name>.vcxproj\n"
"        -<project-name>.vcxproj.user\n"
"      +android\n"
"        +jni\n"
"          -Android.mk\n"
"          -Application.mk\n"
"        +res\n"
"          +drawable-hdpi\n"
"            -icon.png\n"
"          +drawable-ldpi\n"
"            -icon.png\n"
"          +drawable-mdpi\n"
"            -icon.png\n"
"          +drawable-xhdpi\n"
"            -icon.png\n"
"          +layout\n"
"            -main.xml\n"
"          +values\n"
"            -strings.xml\n"
"          +xml\n"
"        +src\n"
"          +com\n"
"            +fi\n"
"              +tech\n"
"                -PView.java\n"
"                -PNativeLibrary.java\n"
"                -PContext.java\n"
"                -PActivity.java\n"
"                +app\n"
"                  -App.java <project-name>\n"
"        -AndroidManifest.xml <project-name>\n"
"        -ant.properties\n"
"        -build.bat\n"
"        -build.xml <official-project-name>\n"
"    +res\n"
"    +src\n"
"      -myscene.h <project-description> <company> <author> <email>\n"
"      -myscene.cpp <project-description> <company> <author> <email>\n"
"      -mycontext.h <project-description> <company> <author> <email>\n"
"      -mycontext.cpp <project-description> <company> <author> <email>\n"
"      -pmain.cpp <project-description> <company> <author> <email> <project-name> <project-name> <window-width> <window-height>\n"
"  +data\n"
"  +documents\n";

static char wallpaperProjectConf[] = 
"+<project-name>\n"
"  +application\n"
"    +configs\n"
"      +msvc2012\n"
"        -<project-name>.sln <project-name> <project-name>\n"
"        -<project-name>.vcxproj\n"
"        -<project-name>.vcxproj.user\n"
"      +android\n"
"        +jni\n"
"          -Android.mk\n"
"          -Application.mk\n"
"        +res\n"
"          +drawable-hdpi\n"
"            -icon.png\n"
"          +drawable-ldpi\n"
"            -icon.png\n"
"          +drawable-mdpi\n"
"            -icon.png\n"
"          +drawable-xhdpi\n"
"            -icon.png\n"
"          +layout\n"
"            -main.xml\n"
"          +values\n"
"            -strings.xml <project-name> <company> <project-description> <project-name> <project-name> <official-project-name>\n"
"          +xml\n"
"            -settings.xml\n"
"            -wallpaper_settings.xml <project-name>\n"
"        +src\n"
"          +com\n"
"            +fi\n"
"              +tech\n"
"                -GLWallpaperService.java <project-name> <multisamples>\n"
"                -PNativeLibrary.java\n"
"                -PContext.java\n"
"                -PGLWallpaperService.java\n"
"                +<project-name>\n"
"                  -Paper3D.java <project-name> <project-name>\n"
"                  -Paper3DSettings.java <project-name> <project-name> <official-project-name>\n"
"        -AndroidManifest.xml <project-name> <version>\n"
"        -ant.properties\n"
"        -project.properties\n"
"        -proguard.cfg\n"
"        -build.bat\n"
"        -build.xml <official-project-name>\n"
"    +res\n"
"      +material\n"
"        -texture.pmt\n"
"      +texture\n"
"        -bg_d_0.png\n"
"        -cao_d_0.png\n"
"        -floor_d_0.png\n"
"        -mogu.png\n"
"        -water.png\n"
"      +mesh\n"
"        -cao.pmh\n"
"        -floor.pmh\n"
"        -mogu.pmh\n"
"        -water.pmh\n"
"      -scene.psc\n"
"    +src\n"
"      -main.cpp <file-header>\n"
"      -myscene.h <file-header>\n"
"      -myscene.cpp <file-header>\n"
"      -mycontext.h <file-header>\n"
"      -mycontext.cpp <file-header>\n"
"      -pmain.cpp <file-header> <project-name> <project-name> <window-width> <window-height> <multisamples> <maxfps>\n"
"  +data\n"
"  +documents\n";

static char applicationProjectConf[] = 
"+<project-name>\n"
"  +application\n"
"    +configs\n"
"      +msvc2012\n"
"        -<project-name>.sln <project-name> <project-name>\n"
"        -<project-name>.vcxproj\n"
"        -<project-name>.vcxproj.user\n"
"      +android\n"
"        +jni\n"
"          -Android.mk\n"
"          -Application.mk\n"
"        +res\n"
"          +drawable-hdpi\n"
"            -icon.png\n"
"          +drawable-ldpi\n"
"            -icon.png\n"
"          +drawable-mdpi\n"
"            -icon.png\n"
"          +drawable-xhdpi\n"
"            -icon.png\n"
"          +layout\n"
"            -main.xml\n"
"          +values\n"
"            -strings.xml <project-name> <company> <project-description> <project-name> <project-name> <official-project-name>\n"
"          +xml\n"
"        +src\n"
"          +com\n"
"            +fi\n"
"              +tech\n"
"                -PView.java <multisamples>\n"
"                -PNativeLibrary.java\n"
"                -PContext.java\n"
"                -PActivity.java <project-name>\n"
"                +<project-name>\n"
"                  -Paper3D.java <project-name> <project-name>\n"
"        -AndroidManifest.xml <project-name> <version>\n"
"        -ant.properties\n"
"        -project.properties\n"
"        -proguard.cfg\n"
"        -build.bat\n"
"        -build.xml <official-project-name>\n"
"    +res\n"
"      +material\n"
"        -texture.pmt\n"
"      +texture\n"
"        -bg_d_0.png\n"
"        -cao_d_0.png\n"
"        -floor_d_0.png\n"
"        -mogu.png\n"
"        -water.png\n"
"      +mesh\n"
"        -cao.pmh\n"
"        -floor.pmh\n"
"        -mogu.pmh\n"
"        -water.pmh\n"
"      -scene.psc\n"
"    +src\n"
"      -main.cpp <file-header>\n"
"      -myscene.h <file-header>\n"
"      -myscene.cpp <file-header>\n"
"      -mycontext.h <file-header>\n"
"      -mycontext.cpp <file-header>\n"
"      -pmain.cpp <file-header> <project-name> <project-name> <window-width> <window-height> <multisamples> <maxfps>\n"
"  +data\n"
"  +documents\n";

#endif // !PROJECT_H
