
const char *MATERIAL_TEXT= 
"<material>\n"
"  <shader>\n"
"    <vs>\n"
"      uniform mat4 MVP;\n"
"\n"
"      attribute mediump vec4 position;\n"
"      attribute mediump vec4 texcoord0;\n"
"\n"
"      varying mediump vec4 vTexCoord;\n"
"\n"
"      void main()\n"
"      {\n"
"          gl_Position = MVP * position;\n"
"          vTexCoord = texcoord0;\n"
"      }\n"
"    </vs>\n"
"    <fs>\n"
"      precision mediump float;\n"
"\n"
"      uniform sampler2D Texture;\n"
"\n"
"      varying mediump vec4 vTexCoord;\n"
"\n"
"      void main()\n"
"      {\n"
"          gl_FragColor = texture2D(Texture, vTexCoord.xy);\n"
"      }\n"
"    </fs>\n"
"  </shader>\n"
"  <parameters>\n"
"    <parameter name=\"mvp\" uniform=\"MVP\" source=\"transform\"/>\n"
"    <parameter name=\"texture\" uniform=\"Texture\" source=\"material\"/>\n"
"  </parameters>\n"
"</material>\n";
