#ifndef WALLPAPER_HEADERS_H
#define WALLPAPER_HEADERS_H

namespace wallpaper
{
    #include "androidmanifestxml.h"
    #include "androidmk.h"
    #include "antproperties.h"
    #include "applicationmk.h"
    #include "msvc2012sln.h"
    #include "msvc2012vcxproj.h"
    #include "msvc2012vcxprojuser.h"
    #include "buildbat.h"
    #include "buildxml.h"
    #include "glwallpaperservicejava.h"
    #include "mainxml.h"
    #include "mycontextcpp.h"
    #include "mycontexth.h"
    #include "myscenecpp.h"
    #include "mysceneh.h"
    #include "pcontextjava.h"
    #include "pglwallpaperservicejava.h"
    #include "paper3dwallpaperjava.h"
    #include "paper3dwallpapersettingsjava.h"
    #include "pmaincpp.h"
    #include "pnativelibraryjava.h"
    #include "projectproperties.h"
    #include "settingsxml.h"
    #include "stringsxml.h"
    #include "wallpaper_settingsxml.h"
    #include "iconpng.h"
    #include "bg_d_0png.h"
    #include "cao_d_0png.h"
    #include "floor_d_0png.h"
    #include "mogupng.h"
    #include "waterpmh.h"
    #include "maincpp.h"
    #include "texturepmt.h"
    #include "scenepsc.h"
    #include "waterpng.h"
    #include "mogupmh.h"
    #include "floorpmh.h"
    #include "proguardcfg.h"
    #include "caopmh.h"
};

#endif // !WALLPAPER_HEADERS_H
