const char MYCONTEXTH_STR[] = 
"// mycontext.h\n"
"%s\n"
"//\n"
"\n"
"#ifndef MYCONTEXT_H\n"
"#define MYCONTEXT_H\n"
"\n"
"#include <PFoundation/pcontext.h>\n"
"#include <PFoundation/pcontextproperties.h>\n"
"\n"
"class MyScene;\n"
"\n"
"class MyContext : public PContext\n"
"{\n"
"public:\n"
"    MyContext(const PContextProperties &properties);\n"
"    ~MyContext();\n"
"    \n"
"    virtual pbool onInitialized();\n"
"    virtual pbool onUpdate();\n"
"    virtual void onDestroy();\n"
"    \n"
"    virtual pbool onKeyboard(PEvent *event);\n"
"\n"
"private:\n"
"    MyScene *m_scene;\n"
"};\n"
"\n"
"#endif\n"
;
