const char PAPER3DWALLPAPERSETTINGSJAVA_STR[] = 
"/*\n"
" * Copyright 2012 - 2014 by Future Interface. \n"
" * This software is licensed under the terms of the MIT license.\n"
" *\n"
" */\n"
"package com.fi.tech.%s;\n"
"\n"
"import com.fi.tech.%s.R;\n"
"\n"
"import android.content.SharedPreferences;\n"
"import android.os.Bundle;\n"
"import android.preference.PreferenceActivity;\n"
"import android.util.Log;\n"
"\n"
"public class Paper3DSettings extends PreferenceActivity\n"
"    implements SharedPreferences.OnSharedPreferenceChangeListener \n"
"{\n"
"\n"
"    @Override\n"
"    protected void onCreate(Bundle icicle) \n"
"    {\n"
"        super.onCreate(icicle);\n"
"        Log.i(\"Paper3D\",\"**********************************\");\n"
"        getPreferenceManager().setSharedPreferencesName(\"%sSettings\");\n"
"        addPreferencesFromResource(R.xml.settings);\n"
"        getPreferenceManager().getSharedPreferences().registerOnSharedPreferenceChangeListener(this);\n"
"    }\n"
"\n"
"    @Override\n"
"    protected void onResume() \n"
"    {\n"
"        super.onResume();\n"
"    }\n"
"\n"
"    @Override\n"
"    protected void onDestroy() \n"
"    {\n"
"        getPreferenceManager().getSharedPreferences().unregisterOnSharedPreferenceChangeListener(this);\n"
"        super.onDestroy();\n"
"    }\n"
"\n"
"    public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String key) \n"
"    {\n"
"    }\n"
"}\n"
;
