const char PAPER3DWALLPAPERJAVA_STR[] = 
"/*\n"
" * Copyright 2012 - 2014 Future Interface. \n"
" * This software is licensed under the terms of the MIT license.\n"
" */\n"
"package com.fi.tech.%s;\n"
"\n"
"import android.content.SharedPreferences;\n"
"import android.content.SharedPreferences.OnSharedPreferenceChangeListener;\n"
"\n"
"import com.fi.tech.PGLWallpaperService;\n"
"\n"
"public class Paper3D extends PGLWallpaperService implements OnSharedPreferenceChangeListener\n"
"{\n"
"    public static final String CONTEXT_NAME = \"%s\";\n"
"    private SharedPreferences mPrefs;\n"
"\n"
"    public Paper3D ()\n"
"    {\n"
"        super();\n"
"    }\n"
"\n"
"    @Override\n"
"    public void onCreate()\n"
"    {\n"
"        super.onCreate();\n"
"        \n"
"        mPrefs = getSharedPreferences(SHARED_PREFS_NAME, 0);\n"
"        mPrefs.registerOnSharedPreferenceChangeListener(this);\n"
"    }\n"
"	\n"
"    @Override\n"
"    public void onSharedPreferenceChanged(SharedPreferences prefs, String key)\n"
"    {\n"
"    }\n"
"}\n"
;
