const char PGLWALLPAPERSERVICEJAVA_STR[] = 
"/*\n"
" * Copyright 2012 - 2014 by Future Interface. \n"
" * This software is licensed under the terms of the MIT license.\n"
" */\n"
"\n"
"package com.fi.tech;\n"
"\n"
"import java.util.Calendar;\n"
"import java.util.GregorianCalendar;\n"
"\n"
"import android.os.Debug;\n"
"import android.util.Log;\n"
"\n"
"public abstract class PGLWallpaperService extends GLWallpaperService \n"
"{\n"
"    public static final boolean DEBUG = true;\n"
"    public String PACKAGE_NAME;\n"
"\n"
"    public PGLWallpaperService() \n"
"    {\n"
"        super();\n"
"    }\n"
"\n"
"    public void onCreate() \n"
"    {\n"
"        Log.i(\"Paper3D\", \"onCreate()\");\n"
"        PACKAGE_NAME = super.getPackageName();\n"
"        //if (DEBUG) \n"
"        //{\n"
"        //    Debug.startMethodTracing(\"paper3d\");\n"
"        //}\n"
"\n"
"        super.onCreate();\n"
"\n"
"        PNativeLibrary nativeLibrary = PNativeLibrary.getInstance();\n"
"        nativeLibrary.initialize(this);\n"
"        if (!nativeLibrary.isInitialized())\n"
"        {\n"
"            Log.e(\"Paper3D\", \"Failed to initialize native library. Quitting.\");\n"
"            stopSelf();\n"
"        }\n"
"    }\n"
"\n"
"    public void onDestroy() \n"
"    {\n"
"        Log.i(\"Paper3D\", \"onDestroy()\");\n"
"\n"
"        super.onDestroy();\n"
"\n"
"        //if (DEBUG) \n"
"        //{\n"
"        //    Debug.stopMethodTracing();\n"
"        //}\n"
"        \n"
"        PNativeLibrary.getInstance().uninitialize();\n"
"    }\n"
"\n"
"    public int getDay() \n"
"    {\n"
"        final Calendar c = GregorianCalendar.getInstance();\n"
"        return c.get(Calendar.DAY_OF_WEEK);\n"
"    }\n"
"\n"
"    public int getDateDay() \n"
"    {\n"
"        final Calendar c = GregorianCalendar.getInstance();\n"
"        return c.get(Calendar.DAY_OF_MONTH);\n"
"    }\n"
"\n"
"    public int getDateMonth() \n"
"    {\n"
"        final Calendar c = GregorianCalendar.getInstance();\n"
"        return c.get(Calendar.MONTH);\n"
"    }\n"
"\n"
"    public int getDateYear() \n"
"    {\n"
"        final Calendar c = GregorianCalendar.getInstance();\n"
"        return c.get(Calendar.YEAR);\n"
"    }\n"
"\n"
"    @Override\n"
"    public Engine onCreateEngine() \n"
"    {\n"
"        Log.i(\"Paper3D\", \"onCreateEngine()\");\n"
"        PEngine engine = new PEngine();\n"
"        return engine;\n"
"    }\n"
"\n"
"    class PEngine extends GLEngine \n"
"    {\n"
"        public PEngine() \n"
"        {\n"
"            super();\n"
"        }\n"
"    }\n"
"}\n"
;
